### ISSUE TITLE
Cant run in eclipse ide

### ISSUE THREAD

**Issue by 488442** [alirezaalj/Oauth2-Authorization-Project#1]
Hi, nice job and thank you for sharing. It's really interesting !!
Can i ask you a details for run the project inside eclipse ide?
This happen when authorization-server running

Description:
Parameter 0 of constructor in ir.alirezaalijani.security.authorization.service.security.config.AttemptFilterConfig required a bean of type 'ir.alirezaalijani.security.authorization.service.security.service.attempt.LoginAttemptService' that could not be found.

Action:
Consider defining a bean of type 'ir.alirezaalijani.security.authorization.service.security.service.attempt.LoginAttemptService' in your configuration.

Really ty

**Comment by alirezaalj** [comment]
Hi, thank you for viewed the project.
About the problem that happened to you: #1 
This project is written in the form of a microservice, and to run it in development mode, you must run the servers in order.
The first project you need to run is config-server
And you must create the config repository before running the config service

`cd Spring-Security-Authorization-Service/conf`
`cp config-repository-copy/* config-repository/`
`cd config-repository`
`git init`
`git add .`
`git commit -m "Initial commit" `
`cd ..`

After making the above configs, the configuration service is ready to run, and of course, make sure to do the configurations inside the files. For example, email, recaptcha for your domain

then you can run authorization-server

and I will commit a cleaner and better version as soon as possible.

**Comment by 488442** [comment]
First of all, thanks for the answer. I am really interested in the project but I have several problems.
Specifically, if I understand correctly, you also refer to this project. It's correct?
https://github.com/alirezaalj/Spring-Security-Authorization-Service

despite your description I struggle to understand what to do. Specifically, I copied the folder in the config-server as in the picture but without success with the same error.
Please kindly help me. thanks as always, you are unique!
![image](https://user-images.githubusercontent.com/46416193/181312926-a1eb705f-537b-4d9d-b5c5-d655d2e235e9.png)

**Comment by 488442** [comment]
![image](https://user-images.githubusercontent.com/46416193/181342047-2d37c647-9396-44a1-803a-4565f4910388.png)
![image](https://user-images.githubusercontent.com/46416193/181342107-e1a08c3f-afea-4b2c-b301-680f18adc1a0.png)

**Comment by 488442** [comment]
![image](https://user-images.githubusercontent.com/46416193/181343499-282d170c-a521-44a9-9179-3062519c88fc.png)
![image](https://user-images.githubusercontent.com/46416193/181343533-193178d0-fb9d-44f8-b0a6-d6a9b8220000.png)

**Comment by alirezaalj** [comment]
hi, new update is commit start read from [Run in development mode](https://github.com/alirezaalj/Oauth2-Authorization-Project#run-in-development-mode)

**Comment by alirezaalj** [comment]
![Screenshot_20220728_013643](https://user-images.githubusercontent.com/53636941/181373089-cac2b326-87a4-44a2-a65a-c302b3e8a292.png)
In this part your problem with above errors will be solved

**Comment by 488442** [comment]
thanks again, as always you are fantastic and very fast in replying.  I'll try the changes tomorrow.  I really want to have a reference project like yours.  thanks again I'll keep you updated

**Comment by 488442** [comment]
Thanks as always but unfortunately nothing to do, I also outsourced the config-server but still the same problem. I hope I will see the project work; (

**Comment by 488442** [comment]
Ty for all i solved the problem with this fix:
1) Using external configuration server via github
2) Adding conf/keys folder inside oauth server.
You are fantastic ;)
